name: nw-toolkit
on:
  pull_request:
    branches:
      - main
    paths:
      - nw-toolkit/scripts/patch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash
    working-directory: nw-toolkit

jobs:
  patch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0

      - name: Make patches
        if: steps.cache-patches.outputs.cache-hit != 'true'
        run: make patch

      - name: Cache patches
        id: cache-patches
        uses: actions/cache@v3
        with:
          path: nw-toolkit/patches
          key: ${{ runner.os }}-patches

      - name: Commit patches
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          commit_message: "[nw-toolkit] update nw patches"
          target_branch: ${{ github.base_ref }}
